[workspace]
members = [
"crates/spv-patcher",
"crates/patch-binding-location-matching",
"crates/spv-tester",
"crates/spv-benchmark"
]


[workspace.dependencies]
rspirv = "0.11"
thiserror = "1.0"
#spirt = {git = "https://github.com/EmbarkStudios/spirt.git"}
spirt = {path = "../spirt"}
log = "0.4"
simple_logger = "4.1"
bytemuck = "1"
