[workspace]
members = [
"crates/spv-patcher",
"crates/spv-tester",
"crates/spv-benchmark",
"crates/patch-binding-location-matching",
"crates/patch-decorate-nonuniform",
"crates/patch-function",
"crates/vulkan-patchable-pipeline"
]


[workspace.dependencies]
rspirv = "0.11"
thiserror = "1.0"
#spirt = {git = "https://github.com/EmbarkStudios/spirt.git"}
spirt = {path = "../spirt"}
log = "0.4"
simple_logger = "4.1"
bytemuck = "1"
serde = "1"
serde_json = "1"
#our vulkan runtime
marpii = {git = "https://gitlab.com/tendsinmende/marpii.git"}
marpii-rmg = {git = "https://gitlab.com/tendsinmende/marpii.git"}
marpii-rmg-shared = {git = "https://gitlab.com/tendsinmende/marpii.git"}
marpii-rmg-tasks = {git = "https://gitlab.com/tendsinmende/marpii.git"}
