

#version 460

#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : require

//GLSL Compute shader that adds a constant.
layout(set = 0, binding = 0) buffer SimObjects{
    uint dta[];
} global_buffer;

//running in 64 waves
layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
void main(){
  uint widx = gl_GlobalInvocationID.x;;

  if (widx >= 1024){
      return;
  }

  const uint i = 1;
  global_buffer.dta[widx] += i;
}
